<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CSharpFunctionalExtensions" Version="3.6.0" />
    <PackageVersion Include="Dapper" Version="2.1.66" />
    <PackageVersion Include="EduardNikitin.Core" Version="0.0.1" />
    <PackageVersion Include="EduardNikitin.FileService.Communication" Version="0.0.2" />
    <PackageVersion Include="EduardNikitin.Framework" Version="0.0.3" />
    <PackageVersion Include="EduardNikitin.SharedKernel" Version="0.0.1" />
    <PackageVersion Include="FluentValidation" Version="12.1.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Routing" Version="2.3.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Routing.Abstractions" Version="2.3.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0-rc.2.25502.107" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
  </ItemGroup>
</Project>