<Project Sdk="Microsoft.NET.Sdk">
  
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Exceptions.EntityFrameworkCore" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"/>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Shared.SharedKernel\Shared.SharedKernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>EduardNikitin.Framework</PackageId>
    <Version>0.0.3</Version>
    <Authors>EduardNikitin</Authors>
    <Company>EduardNikitin</Company>
    <PackageDescription>Framework</PackageDescription>
    <RepositoryUrl>https://gitlab.com/EduardNikitin/mindhub</RepositoryUrl>
  </PropertyGroup>
</Project>
