<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <PackageId>EduardNikitin.FileService.Communication</PackageId>
      <Version>0.0.2</Version>
      <Authors>EduardNikitin</Authors>
      <Company>EduardNikitin</Company>
      <PackageDescription>Communication FileService project</PackageDescription>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" />
      <PackageReference Include="EduardNikitin.SharedKernel" />
      <PackageReference Include="Microsoft.Extensions.Http" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    </ItemGroup>

</Project>
