<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EducationContentService.Core\EducationContentService.Core.csproj" />
    <ProjectReference Include="..\EducationContentService.Domain\EducationContentService.Domain.csproj" />
    <ProjectReference Include="..\EducationContentService.Infrastructure.Postgres\EducationContentService.Infrastructure.Postgres.csproj" />
  </ItemGroup>


</Project>
